### ISSUE TITLE
Returns an error when downloading files from Google Drive

### ISSUE THREAD

**Issue by ciriousjoker** [hxsf/download-file-with-progressbar#1]
Returns "File validation failed" (<= The chinese equivalent) when downloading files from Google Drive.

This is probably due to GDrive not reporting the total filesize.
The downloads do work as expected though, just the last check fails because "total" = NaN

Edited the dl.js manually and opened a pull request. This pull request is untested but should do its job. Please verify that though before merging it. I am not responsible if this doesn't work!

**Comment by hxsf** [comment]
Thanks for your pr !
